server:
  port: 8085

spring:
  application:
    name: anax-kogito-sample
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

kogito:
  workflow:
    version-strategy: workflow

anax:
  catalog:
    enabled: true
